-- require("null-ls").setup({
--     sources = {
--         require("null-ls").builtins.diagnostics.tidy,
--         require("null-ls").builtins.formatting.autopep8,
--
--     },
-- })
--
-- vim.diagnostic.config({
--     virtual_text = {
--         -- prefix = '■', -- Could be '●', '▎', 'x'
--         prefix = 'x'
--     }
-- })
--
-- local signs = { Error = " ", Warn = "⚠ ", Hint = " ", Info = " " }
-- for type, icon in pairs(signs) do
--     local hl = "DiagnosticSign" .. type
--     vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
-- end
--
--
-- local defaults = {
--     cmd = { "nvim" },
--     debounce = 250,
--     debug = false,
--     default_timeout = 5000,
--     diagnostics_format = "#{m} alllahlkfdshlfd",
--     fallback_severity = vim.diagnostic.severity.ERROR,
--     log_level = "warn",
--     notify_format = "[null-ls] %s",
--     on_attach = nil,
--     on_init = nil,
--     on_exit = nil,
--     sources = nil,
--     update_in_insert = false,
-- }
