-- local db = require('dashboard')
--
-- db.custom_header = {
--  ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
--  ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
--  ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
--  ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
--  ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
--  ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
-- }
--
-- db.custom_center = {
--   { icon = "  ", desc = "File Tree", action = "NvimTreeOpen"},
--   { icon = "  ", desc = "Find files", action = "Telescope find_files hiddent=true"},
--   { icon = "  ", desc = "Recent files", action = "Telescope oldfiles" },
--   { icon = "  ", desc = "New file", action = "enew"},
--   { icon = "  ", desc = "Settings", action = "NvimTreeOpen ~/.config/nvim/"},
-- }
--
-- db.custom_footer = {""}
--
-- -- db.header_pad = 10
-- -- db.center_pad = 5
-- db.footer_pad = 100
