-- local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

-- require('lspconfig')['pylsp'].setup {
--   capabilities = capabilities
-- }
--
-- require('lspconfig')['emmet_ls'].setup {
--   capabilities = capabilities
-- }
--
-- require('lspconfig')['html'].setup {
--   capabilities = capabilities
-- }
--
-- require('lspconfig')['bashls'].setup {
--   capabilities = capabilities
-- }
--
-- require('lspconfig')['sumneko_lua'].setup {
--   capabilities = capabilities
-- }
--

-- local signs = { Error = " ", Warn = " ", Hint = " ", Info = " " }
-- for type, icon in pairs(signs) do
--   local hl = "DiagnosticSign" .. type
--   vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
-- end
